### ISSUE TITLE
Add instructions on how to update Python image and bump Python version

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/wiki#55]
Once in a while we need to update the Python version from old versions that have reached their end of life and are no longer supported and bump Python version in production. Currently these steps are missing and the deploy cycle is prolonged as it will be done on a trial and error version. Steps done to upgrade from Python 3.4 to 3.7 need to be documented in [deploy section](https://github.com/DjangoGirls/wiki/blob/main/howto/deploy-website.md) of the wiki for future support team members to use as reference.

**Comment by das-g** [comment]
This is
- about the Python version for running https://djangogirls.org,
- **not** the [one to be installed by workshop participants](https://tutorial.djangogirls.org/en/python_installation/) (controlled by GitBook variables [here](https://github.com/DjangoGirls/tutorial/blob/3d1231eda8ffc7689fc749dd728039f88fc3bbb7/book.json#L4-L8); last updated with DjangoGirls/tutorial#1683) for following the tutorial,

right?

**Comment by amakarudze** [comment]
Yes @das-g. We just updated the Python version for [https://djangogirls.org](https://djangogirls.org) on PythonAnywhere but it wasn't documented before.
