### ISSUE TITLE
Remove GitHub Sponsorship email guidelines

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/wiki#56]
Since GitHub ceased to support Django Girls events, I think we can remove [these guidelines](https://github.com/DjangoGirls/wiki/blob/main/howto/emails/GitHub_sponsorship.md) since they are now obsolete.

**Comment by das-g** [comment]
(Closely related to #60.)

**Comment by amakarudze** [comment]
Yep I noticed. Will just do 1 PR and close them both.
